version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: hacker-news-app
    environment:
      - PORT=5000
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hacker_news
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: hacker-news-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hacker_news
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
